In [6]:
import pandas as pd 

print("Pandas version:", pd.__version__)

Pandas version: 2.2.3

In [10]:
# Read a CSV file
df = pd.read_csv("dmc2006_train.csv")

# Print the first few rows of the DataFrame
df.head()

,auct_id,item_leaf_category_name,listing_title,listing_subtitle,listing_start_date,listing_end_date,listing_durtn_days,listing_type_code,feedback_score_at_listing_time,start_price,buy_it_now_price,buy_it_now_listed_flag,bold_fee_flag,featured_fee_flag,category_featured_fee_flag,gallery_fee_flag,gallery_featured_fee_flag,ipix_featured_fee_flag,reserve_fee_flag,highlight_fee_flag,schedule_fee_flag,border_fee_flag,qty_available_per_listing,gms,category_avg_gms,gms_greater_avg
0,1,Audio & Hi-Fi:MP3-Player:Apple iPod:iPod Mini ...,Apple iPod mini 4 GB 2. Gen. 2005 silber blau ...,NaN,6/24/05,11/3/05,132,7,2182,195.0,0,N,N,N,N,Y,N,N,N,N,N,N,48,195.0,167.977,1
1,3,Audio & Hi-Fi:MP3-Player:Apple iPod:iPod Mini ...,APPLE iPod mini Musicplayer 4GB Mac/Win USB 2....,NaN,8/13/05,10/11/05,59,7,10604,185.0,0,N,N,N,N,N,N,N,N,N,N,N,2,185.0,167.977,1
2,4,Audio & Hi-Fi:MP3-Player:Apple iPod:iPod Mini ...,Apple iPOD Mini Silber NEUWARE mit Rechnung/Ga...,NaN,9/8/05,10/23/05,45,7,72,195.0,0,N,N,N,N,Y,N,N,N,N,N,N,2,195.0,167.977,1
3,5,Audio & Hi-Fi:MP3-Player:Apple iPod:iPod Mini ...,Apple i-Pod mini 4GB BLUE org. verpackt +Rech...,Neuwertig +Garantie ¸ber Original-Rechnung (Me...,10/14/05,10/24/05,10,1,2,85.0,0,N,Y,N,N,Y,N,Y,N,N,Y,Y,1,172.0,161.512,1
4,6,Audio & Hi-Fi:MP3-Player:Apple iPod:iPod Mini ...,Apple iPod mini 4 GB Rosa,NaN,9/18/05,10/13/05,25,7,136,199.0,0,N,N,N,N,N,N,N,N,N,N,N,1,199.0,173.450,1

In [11]:
df.tail()

,auct_id,item_leaf_category_name,listing_title,listing_subtitle,listing_start_date,listing_end_date,listing_durtn_days,listing_type_code,feedback_score_at_listing_time,start_price,buy_it_now_price,buy_it_now_listed_flag,bold_fee_flag,featured_fee_flag,category_featured_fee_flag,gallery_fee_flag,gallery_featured_fee_flag,ipix_featured_fee_flag,reserve_fee_flag,highlight_fee_flag,schedule_fee_flag,border_fee_flag,qty_available_per_listing,gms,category_avg_gms,gms_greater_avg
7993,15995,Audio & Hi-Fi:MP3-Player:Apple iPod:iPod Nano ...,Apple - iPod NANO 4GB(4 GB) schwarz /NEU/OVP/...,NaN,3/18/06,3/19/06,1,1,2849,1.99,0,N,N,N,N,N,N,N,N,N,N,N,1,213.00,197.862,1
7994,15996,Audio & Hi-Fi:MP3-Player:Apple iPod:iPod Nano ...,Apple - iPod NANO 4GB(4 GB) schwarz /NEU/OVP/...,NaN,3/18/06,3/21/06,3,1,2849,1.99,0,N,N,N,N,N,N,N,N,N,N,N,1,225.00,197.862,1
7995,15997,Audio & Hi-Fi:MP3-Player:Apple iPod:iPod Nano ...,Apple - iPod NANO 4GB(4 GB) schwarz /NEU/OVP/...,NaN,3/18/06,3/23/06,5,1,2849,1.99,0,N,N,N,N,N,N,N,N,N,N,N,1,222.22,197.862,1
7996,15998,Audio & Hi-Fi:MP3-Player:Apple iPod:40 GB,iPod 4.Generation 40GB Defekt fuer bastler,NaN,3/19/06,3/22/06,3,1,53,100.00,180,Y,N,N,N,N,N,Y,N,N,Y,N,1,180.00,221.153,0
7997,16000,Audio & Hi-Fi:MP3-Player:Apple iPod:iPod Nano ...,Apple - iPod NANO 2GB **schwarz** NEU mit Rech...,NaN,3/19/06,3/22/06,3,1,160,1.00,0,N,N,N,N,Y,N,N,N,N,N,N,1,165.01,166.481,0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7998 entries, 0 to 7997
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   auct_id                         7998 non-null   int64
 1   item_leaf_category_name         7998 non-null   object
 2   listing_title                   7998 non-null   object
 3   listing_subtitle                1050 non-null   object
 4   listing_start_date              7998 non-null   object
 5   listing_end_date                7998 non-null   object
 6   listing_durtn_days              7998 non-null   int64
 7   listing_type_code               7998 non-null   int64
 8   feedback_score_at_listing_time  7998 non-null   int64
 9   start_price                     7998 non-null   float64
 10  buy_it_now_price                7998 non-null   int64
 11  buy_it_now_listed_flag          7998 non-null   object
 12  bold_fee_flag                   7998 non-null   object
 13  featured_fee_flag               7998 non-null   object
 14  category_featured_fee_flag      7998 non-null   object
 15  gallery_fee_flag                7998 non-null   object
 16  gallery_featured_fee_flag       7998 non-null   object
 17  ipix_featured_fee_flag          7998 non-null   object
 18  reserve_fee_flag                7998 non-null   object
 19  highlight_fee_flag              7998 non-null   object
 20  schedule_fee_flag               7998 non-null   object
 21  border_fee_flag                 7998 non-null   object
 22  qty_available_per_listing       7998 non-null   int64
 23  gms                             7880 non-null   float64
 24  category_avg_gms                7998 non-null   float64
 25  gms_greater_avg                 7998 non-null   int64
dtypes: float64(3), int64(7), object(16)
memory usage: 1.6+ MB