In [1]:
import pandas as pd; pd.options.display.max_columns = None

# Read the CSV file
df = pd.read_csv('dmc2006_train.csv')
df.head()

,auct_id,item_leaf_category_name,listing_title,listing_subtitle,listing_start_date,listing_end_date,listing_durtn_days,listing_type_code,feedback_score_at_listing_time,start_price,buy_it_now_price,buy_it_now_listed_flag,bold_fee_flag,featured_fee_flag,category_featured_fee_flag,gallery_fee_flag,gallery_featured_fee_flag,ipix_featured_fee_flag,reserve_fee_flag,highlight_fee_flag,schedule_fee_flag,border_fee_flag,qty_available_per_listing,gms,category_avg_gms,gms_greater_avg
0,1,Audio & Hi-Fi:MP3-Player:Apple iPod:iPod Mini ...,Apple iPod mini 4 GB 2. Gen. 2005 silber blau ...,NaN,6/24/05,11/3/05,132,7,2182,195.0,0,N,N,N,N,Y,N,N,N,N,N,N,48,195.0,167.977,1
1,3,Audio & Hi-Fi:MP3-Player:Apple iPod:iPod Mini ...,APPLE iPod mini Musicplayer 4GB Mac/Win USB 2....,NaN,8/13/05,10/11/05,59,7,10604,185.0,0,N,N,N,N,N,N,N,N,N,N,N,2,185.0,167.977,1
2,4,Audio & Hi-Fi:MP3-Player:Apple iPod:iPod Mini ...,Apple iPOD Mini Silber NEUWARE mit Rechnung/Ga...,NaN,9/8/05,10/23/05,45,7,72,195.0,0,N,N,N,N,Y,N,N,N,N,N,N,2,195.0,167.977,1
3,5,Audio & Hi-Fi:MP3-Player:Apple iPod:iPod Mini ...,Apple i-Pod mini 4GB BLUE org. verpackt +Rech...,Neuwertig +Garantie ¸ber Original-Rechnung (Me...,10/14/05,10/24/05,10,1,2,85.0,0,N,Y,N,N,Y,N,Y,N,N,Y,Y,1,172.0,161.512,1
4,6,Audio & Hi-Fi:MP3-Player:Apple iPod:iPod Mini ...,Apple iPod mini 4 GB Rosa,NaN,9/18/05,10/13/05,25,7,136,199.0,0,N,N,N,N,N,N,N,N,N,N,N,1,199.0,173.450,1

In [3]:
df["start_price"].describe()

count    7998.000000
mean       45.572354
std        82.163806
min         1.000000
25%         1.000000
50%         1.000000
75%        50.000000
max       414.000000
Name: start_price, dtype: float64

In [ ]:
# Selecting items with start_price greater than 300
df[df["start_price"]>300].head()

,auct_id,item_leaf_category_name,listing_title,listing_subtitle,listing_start_date,listing_end_date,listing_durtn_days,listing_type_code,feedback_score_at_listing_time,start_price,buy_it_now_price,buy_it_now_listed_flag,bold_fee_flag,featured_fee_flag,category_featured_fee_flag,gallery_fee_flag,gallery_featured_fee_flag,ipix_featured_fee_flag,reserve_fee_flag,highlight_fee_flag,schedule_fee_flag,border_fee_flag,qty_available_per_listing,gms,category_avg_gms,gms_greater_avg
304,599,Audio & Hi-Fi:MP3-Player:Apple iPod:40 GB,Apple iPod Photo / Farbdisplay 40 GB / 5. GEN....,NaN,10/13/05,10/16/05,3,1,48,329.0,349,Y,N,N,N,Y,N,N,N,N,Y,N,1,349.0,221.153,1
407,799,Audio & Hi-Fi:MP3-Player:Apple iPod:40 GB,"Apple iPod PHOTO 40GB *Topmodel,5.Gen.,OVP*",+viel Zubehˆr im Wert von ca. 100ˇ,10/17/05,10/27/05,10,1,122,329.0,349,Y,Y,N,N,Y,N,Y,N,N,N,N,1,NaN,221.153,0
820,1645,Audio & Hi-Fi:MP3-Player:Apple iPod:30 GB,APPLE IPOD VIDEO 30GB *NEU* Orignal + Rechnung,NaN,11/8/05,11/9/05,1,9,445,309.9,0,N,N,N,N,Y,N,N,N,N,N,Y,1,309.9,263.459,1
1862,3729,Audio & Hi-Fi:MP3-Player:Apple iPod:40 GB,"APPLE I-POD 40GB , Zubehˆr, OVP",NaN,12/10/05,12/18/05,8,9,3800,320.0,0,N,N,N,N,N,N,Y,N,N,N,N,1,320.0,221.153,1
2273,4580,Audio & Hi-Fi:MP3-Player:Apple iPod:40 GB,Apple iPod Video 60 GB schwarz --NEU--,NaN,12/20/05,12/20/05,0,1,12,350.0,390,Y,N,N,N,N,N,N,N,N,N,N,1,390.0,221.153,1

In [9]:
# Selecting items with start_price greater than 300
df.query("start_price>300").head()

,auct_id,item_leaf_category_name,listing_title,listing_subtitle,listing_start_date,listing_end_date,listing_durtn_days,listing_type_code,feedback_score_at_listing_time,start_price,buy_it_now_price,buy_it_now_listed_flag,bold_fee_flag,featured_fee_flag,category_featured_fee_flag,gallery_fee_flag,gallery_featured_fee_flag,ipix_featured_fee_flag,reserve_fee_flag,highlight_fee_flag,schedule_fee_flag,border_fee_flag,qty_available_per_listing,gms,category_avg_gms,gms_greater_avg
304,599,Audio & Hi-Fi:MP3-Player:Apple iPod:40 GB,Apple iPod Photo / Farbdisplay 40 GB / 5. GEN....,NaN,10/13/05,10/16/05,3,1,48,329.0,349,Y,N,N,N,Y,N,N,N,N,Y,N,1,349.0,221.153,1
407,799,Audio & Hi-Fi:MP3-Player:Apple iPod:40 GB,"Apple iPod PHOTO 40GB *Topmodel,5.Gen.,OVP*",+viel Zubehˆr im Wert von ca. 100ˇ,10/17/05,10/27/05,10,1,122,329.0,349,Y,Y,N,N,Y,N,Y,N,N,N,N,1,NaN,221.153,0
820,1645,Audio & Hi-Fi:MP3-Player:Apple iPod:30 GB,APPLE IPOD VIDEO 30GB *NEU* Orignal + Rechnung,NaN,11/8/05,11/9/05,1,9,445,309.9,0,N,N,N,N,Y,N,N,N,N,N,Y,1,309.9,263.459,1
1862,3729,Audio & Hi-Fi:MP3-Player:Apple iPod:40 GB,"APPLE I-POD 40GB , Zubehˆr, OVP",NaN,12/10/05,12/18/05,8,9,3800,320.0,0,N,N,N,N,N,N,Y,N,N,N,N,1,320.0,221.153,1
2273,4580,Audio & Hi-Fi:MP3-Player:Apple iPod:40 GB,Apple iPod Video 60 GB schwarz --NEU--,NaN,12/20/05,12/20/05,0,1,12,350.0,390,Y,N,N,N,N,N,N,N,N,N,N,1,390.0,221.153,1

In [11]:
# Selecting items with start_price greater than 300 and gms_greater_avg equals 1
df[(df["start_price"]>300) & (df["gms_greater_avg"]==1)].head()

,auct_id,item_leaf_category_name,listing_title,listing_subtitle,listing_start_date,listing_end_date,listing_durtn_days,listing_type_code,feedback_score_at_listing_time,start_price,buy_it_now_price,buy_it_now_listed_flag,bold_fee_flag,featured_fee_flag,category_featured_fee_flag,gallery_fee_flag,gallery_featured_fee_flag,ipix_featured_fee_flag,reserve_fee_flag,highlight_fee_flag,schedule_fee_flag,border_fee_flag,qty_available_per_listing,gms,category_avg_gms,gms_greater_avg
304,599,Audio & Hi-Fi:MP3-Player:Apple iPod:40 GB,Apple iPod Photo / Farbdisplay 40 GB / 5. GEN....,NaN,10/13/05,10/16/05,3,1,48,329.00,349,Y,N,N,N,Y,N,N,N,N,Y,N,1,349.00,221.153,1
820,1645,Audio & Hi-Fi:MP3-Player:Apple iPod:30 GB,APPLE IPOD VIDEO 30GB *NEU* Orignal + Rechnung,NaN,11/8/05,11/9/05,1,9,445,309.90,0,N,N,N,N,Y,N,N,N,N,N,Y,1,309.90,263.459,1
1862,3729,Audio & Hi-Fi:MP3-Player:Apple iPod:40 GB,"APPLE I-POD 40GB , Zubehˆr, OVP",NaN,12/10/05,12/18/05,8,9,3800,320.00,0,N,N,N,N,N,N,Y,N,N,N,N,1,320.00,221.153,1
2273,4580,Audio & Hi-Fi:MP3-Player:Apple iPod:40 GB,Apple iPod Video 60 GB schwarz --NEU--,NaN,12/20/05,12/20/05,0,1,12,350.00,390,Y,N,N,N,N,N,N,N,N,N,N,1,390.00,221.153,1
2360,4752,Audio & Hi-Fi:MP3-Player:Apple iPod:40 GB,Apple iPod 40GB,NaN,12/22/05,12/27/05,5,9,0,329.99,0,N,N,N,N,Y,N,N,N,N,N,N,1,329.99,221.153,1

In [12]:
# Selecting items with start_price greater than 300 and gms_greater_avg equals 1
df.query("start_price>300 and gms_greater_avg==1").head()

,auct_id,item_leaf_category_name,listing_title,listing_subtitle,listing_start_date,listing_end_date,listing_durtn_days,listing_type_code,feedback_score_at_listing_time,start_price,buy_it_now_price,buy_it_now_listed_flag,bold_fee_flag,featured_fee_flag,category_featured_fee_flag,gallery_fee_flag,gallery_featured_fee_flag,ipix_featured_fee_flag,reserve_fee_flag,highlight_fee_flag,schedule_fee_flag,border_fee_flag,qty_available_per_listing,gms,category_avg_gms,gms_greater_avg
304,599,Audio & Hi-Fi:MP3-Player:Apple iPod:40 GB,Apple iPod Photo / Farbdisplay 40 GB / 5. GEN....,NaN,10/13/05,10/16/05,3,1,48,329.00,349,Y,N,N,N,Y,N,N,N,N,Y,N,1,349.00,221.153,1
820,1645,Audio & Hi-Fi:MP3-Player:Apple iPod:30 GB,APPLE IPOD VIDEO 30GB *NEU* Orignal + Rechnung,NaN,11/8/05,11/9/05,1,9,445,309.90,0,N,N,N,N,Y,N,N,N,N,N,Y,1,309.90,263.459,1
1862,3729,Audio & Hi-Fi:MP3-Player:Apple iPod:40 GB,"APPLE I-POD 40GB , Zubehˆr, OVP",NaN,12/10/05,12/18/05,8,9,3800,320.00,0,N,N,N,N,N,N,Y,N,N,N,N,1,320.00,221.153,1
2273,4580,Audio & Hi-Fi:MP3-Player:Apple iPod:40 GB,Apple iPod Video 60 GB schwarz --NEU--,NaN,12/20/05,12/20/05,0,1,12,350.00,390,Y,N,N,N,N,N,N,N,N,N,N,1,390.00,221.153,1
2360,4752,Audio & Hi-Fi:MP3-Player:Apple iPod:40 GB,Apple iPod 40GB,NaN,12/22/05,12/27/05,5,9,0,329.99,0,N,N,N,N,Y,N,N,N,N,N,N,1,329.99,221.153,1